# Generated by Django 4.2.5 on 2024-03-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='ordered_at',
            new_name='ordered',
        ),
    ]
